### ISSUE TITLE
design & implement messaging v1

### ISSUE THREAD

**Issue by cbosborn** [dialectlabs/protocol#26]
# tasks
- [ ] standard dialect
  - [ ] account & metadata
    - [x] members (2 for now)
    - [x] scopes
    - [x] deterministic PDA for efficient address discovery (seeds sorting)
    - [ ] messages
      - [ ] text
      - [ ] length
        - [ ] ring
        - [ ] variable allocation?
      - [ ] metadata?
        - [ ] type (e.g. payment requests, etc.)
    - [ ] encrypted
    - [ ] space
  - [ ] profile
    - [ ] dialects
    - [ ] device-token
  - [ ] invites?
    - [ ] invite user stories
    - [ ] program accounts query for membership
    - [ ] tokens?
    - [ ] memos?
  - [ ] encryption
    - [ ] user settings with dialect
  - [ ] lifecycle
    - [ ] delete
    - [ ] update?
- [ ] token dialect (TBD)

### `text`

So for 256-byte messages, 39 messages would fit into 10kb (just under the limit)
